language: python
python:
- '3.5'
script: make tests
cache: pip
deploy:
  provider: heroku
  app:
    master: crayons
  api_key:
    secure: GpaQsXr7S+yqIdsMOUrI4W8Vy1O05UG77bKv0ZN2/Ae2M+m0orUfVOlpm7iIaz6mhcjw9JQb3wS8gtd7Pmv2wBVPWX9GbJqm8t+LnfN1fyLos0d0BQIKCRDAJrz6/dDIURy2LdEzPnJGFeAn7eoq7uIhVGhEdKgxT9XIyO6vSdjETLbgdsRMxE874tehlBtGo+f/dwbdonDXw43QTb+FAc+VrnqUwpeL+Qk8XgNoVyZ12LXuYTQLYtrptsJyqE26ReBrmDit5U0WiLC5+ZKNV8VeiA20Huzr5G8OmtGybhFpu6nvdjysXURjbBjYbLfgZ95Xk56wzQAay2Df+xHu+p/nCTT32yTNBu5BiR72ujaygpm3ISe2v78zy+Lvs0HdOF0ioz4HS/sMNrtm/mX7SWlRR98MfzK+nRgwlqgomWaFsjBApThY4L0taGN7e1tCCX24umjvaFx8FTsYDjGcAJWwzr7IpAGsjIBB3xXgXtWtJcphV85q97vgKoovzrguVnEsmIqXMadSpmiM+IPqz+RJHfoNurjpFsNnaeXsKaLyt7ZCERuA+x7qSHGQrZHFuZH733SAYm7bzyseBRrqB4RUeNprzvU8ZedWPa6gIah0LgIvgbN8i2196gUXHyWjgWOidfr4yFqiGmiVIpm2YjwIzEXf4K08a+mqJnRCeaU=
